# Generated by Django 3.2 on 2021-05-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210510_1537'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterModelTable(
            name='musician',
            table=None,
        ),
    ]
